### ISSUE TITLE
Support option to prevent linting entire repository when running hhast-lint in LSP mode

### ISSUE THREAD

**Issue by PranayAgarwal** [hhvm/hhast#100]
Large repositories with lots of custom rules aren't going to finish linting in a reasonable amount of time, so LSP mode will need an option to not start a lint run on the entire repository at launch, but rather:

- Lint individual files on open & save
- Remove diagnostics for a file when it is closed

**Comment by fredemmott** [comment]
> so LSP mode will need an option to not start a lint run on the entire repository at launch

Given the out-of-order responses we've now got, the full lint run doesn't block the others, so I don't think this is an issue any more.

That said, this would still be useful for repositories that aren't meant to be lint-error-free; is 'only show lint errors for open files' desired behavior in itself for the repository, regardless of performance?

**Comment by PranayAgarwal** [comment]
Yeah, definitely still useful. Will a full repository run delay getting errors for open files though, or can they be prioritized?
