### ISSUE TITLE
Add linter banning consecutive blank lines

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#109]

**Comment by lexidor** [comment]
Is this something we still want?
Does it need to understand if the `\n\n` appears inside of a string literal?
Most line based linters don't (NoWhiteSpaceAtEndOfLineLinter and friends) also preform their autofixes on (multiline) string literals.

**Comment by jjergus** [comment]
I don't have a strong opinion but I'd guess that there are more valid use cases for consecutive blank lines than there are for whitespace at the end of a line, so I'd definitely exclude string literals from this even if NoWhiteSpaceAtEndOfLineLinter includes them).
