### ISSUE TITLE
Add string interpolation linter

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#11]
We recommend concatenation (or sprintf) instead; this could be an autofixing linter.

**Comment by xixixao** [comment]
Is there a reasoning for this Lint rule? What's the advantage of `"x ".$something." y"` over `"x $something y"`?

Seems that we don't have this enabled at FB. There was some discussion on this, but there doesn't seem to be a difference in type safety.

**Comment by fredemmott** [comment]
That wasn’t the case in 2017; it can be disabled via hhast-lint.json if you don’t want it

**Comment by xixixao** [comment]
Sure, but I like all the rules in the builtin "all" collection - this one is... questionable. One reason I found you could argue is that concatenation allows any expression, while interpolation allows only plain variable references - and so with this lint rule there's "one less" way of doing things. Still feels a bit too weak to include in the default collection.
