### ISSUE TITLE
Add non-autofixing linter for `\HH\Asio\join()`

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#116]
Should:
 - handle if `join` is pulled in via a `use` statement
 - recommend refactoring to async functions and using `await` instead

**Comment by lexidor** [comment]
Imma give this a shot.
I this post is prehistoric (:wave: hi, how's the future?) feel free to bump me or try it yourself.

**Comment by lexidor** [comment]
This linter has been implemented in #274, closing.
