### ISSUE TITLE
Add linters for UNSAFE, UNSAFE_BLOCK, UNSAFE_EXPR and HH_(FIXME|IGNORE_ERROR)[1002]

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#12]
- These should all be separate linters, except for UNSAFE and UNSAFE_BLOCK
 - UNSAFE_EXPR is better than UNSAFE and UNSAFE_EXPR but not as good as FIXME|IGNORE_ERROR
 - using HH_IGNORE_ERROR[1002] or HH_FIXME[1002] suppresses parse errors, so gives you undefined behavior for the rest of the file. The usual reason for ignoring 1002 is pseudomain code in a strict file; the linter should suggest moving most of the code to a separate file, and making the file partial instead

**Comment by lexidor** [comment]
All uses for these linters have been removed in modern Hack.

`UNSAFE(_BLOCK|_EXPR)` are not special anymore. The top-level code ban is enforced by hhvm, so `/*HH_FIXME[1002] */ main()` doesn't work. Banning `HH_FIXME[1002]` completely can be done on a hhconfig level.
