### ISSUE TITLE
Migrations vs codemods

### ISSUE THREAD

**Issue by Daniel15** [hhvm/hhast#126]
From the readme:
> Migrations are for sweeping changes you want to apply across your entire codebase,

Is there a reason we call these "migrations" in this repo? We usually refer to these as "codemods", both internally at Facebook, as well as in other tools that have similar functionality (eg. [jscodeshift](https://github.com/facebook/jscodeshift) for JavaScript, [codemod](https://github.com/facebook/codemod) and [fastmod](https://github.com/facebookincubator/fastmod) for regex-based ones). [Bowler](https://pybowler.io/) calls it "refactoring", which is also fine.

**Comment by fredemmott** [comment]
I wasn't aware we were already using 'codemod'; despite it being used by other FB projects, it still feels like FB-specific jargon. Migrating was meant to be descriptive, as the primary purpose was to deal with migrating code from one version of HHVM to another (e..g 'the shapes migration'). Refactoring also works, but doesn't seem quite as descriptive, and also doesnt' seem worth changing the binaries/API names etc.
