### ISSUE TITLE
Add `instanceof` to `is` migration/linter

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#133]
This is an extension of #132; it's slightly harder as generics need to be potentially handled.

`$x instanceof Foo` might be `$x is Foo`, `$x is Foo<_>`, `$x is Foo<_, _>` etc.

**Comment by lexidor** [comment]
@fredemmott This issue may be closed. You developed this one.

**Comment by fredemmott** [comment]
... and deleted in 6b127b01616bf61139b931200320c901815ecf83 :p
