### ISSUE TITLE
Add 'add use statement/clause' helper, add `use type Facebook\HackTest\DataProvider` when needed in PHPUnit-to-hacktest migrator

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#137]
This would:
- be useful for optional features in 3.29, or for 3.29 => 3.30 migration in the future
- be able to serve as a basis for automatically adding 'use' clauses in other contexts in the future, e.g. when using `Str\`, automatically using `use type HH\Lib\Str`

**Comment by lexidor** [comment]
The PHPUnit migration has been removed.
```
$ hhast-migrate --help
...
--phpunit-to-hacktest
        no longer supported
...
```
