### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by muglug** [hhvm/hhast#147]
- What's `QuestionQuestionEqualToken` for? Doesn't seem supported by the language
 - What's the source of the generated HHAST types/tokens so I can ticket issues (e.g.  `IsExpression` is missing from the list of valid binary op left/right expressions)
-  Is there a list of Hack interfaces that don't need to be fully-qualified (e.g. Awaitable)?

**Comment by fredemmott** [comment]
- the AST definitions include things that might not yet be enabled, or fully implemented. This one should be in 3.30. `$a ??= $b` is /roughly/ equivalent to `$a = $a ?? $b`. An exact equivalent is going to much more verbose, given, `__get`, and `__set`, and expressions like `$x['a']->b['c'] ??= 'foo'` or `$x[$a]->$b[$c] ??= 'foo'`
- `hh_single_compile --schema` for the bulk of the data, https://github.com/hhvm/hhast/blob/15b17a777ecaee959ffcedb67861251a8d1d0f92/src/__Private/codegen/CodegenSyntax.php#L485-L505 for the marker interfaces
- https://github.com/facebook/hhvm/blob/05ae93d6fb4cbc72dc128938f450c92cdfb5a133/hphp/hack/src/parser/namespaces.ml
