### ISSUE TITLE
Case of NULL not preserved

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/hhast#15]
The `NullLiteralToken` always uses `null` for the text, even if the source was using a different case. This means that these all get changed when running a migration, even though it's not related to the migration.

This does not happen with `true`/`false`

```hack
$ cat test.php
<?hh

NULL;
TRUE;
FALSE;
$ bin/hhast-migrate --optional-shape-fields test.php
$ cat test.php
<?hh

null;
TRUE;
FALSE;
```

**Comment by fredemmott** [comment]
Unlike booleans, the FFP schema defines NullLiteralToken as a fixed-text token, so HHAST doesn't bother tracking the actual text - probably should just change HHAST to always track text for all tokens, as there's a fair few "fixed-text" tokens that can actually be used in a case-insensitive manner.
