### ISSUE TITLE
KeysetTypeSpecifier::getType() returns wrong type

### ISSUE THREAD

**Issue by muglug** [hhvm/hhast#150]
I think the following is valid code:

```php
class MyClass {}
function foo(keyset<classname> $bar) {}
function baz(): void {
  foo(keyset[MyClass::class]);
}
```

`KeysetTypeSpecifier::getType` declares a return type of a `SimpleTypeSpecifier`: https://github.com/hhvm/hhast/blob/0c57a0608413924e4d2f9450e5de53d24e54802b/codegen/syntax/KeysetTypeSpecifier.php#L207-L212

But the type in question is a `ClassnameTypeSpecifier`. Related to https://github.com/hhvm/hhast/issues/147, insofar as I couldn't figure out where the bad value comes from.

**Comment by fredemmott** [comment]
There isn't a canonical source of truth that can be used; they're inferred from usage in the HHVM and Hack test suites by the `CodegenRelations` class. It's probably best to add a file to HHAST containing known-missing patterns, for both this and #151
