### ISSUE TITLE
Create more interfaces for commonly grouped node types

### ISSUE THREAD

**Issue by hgoldstein** [hhvm/hhast#167]
It's weird that `BinaryExpression`'s children are not each some sort of "Expression-ish" type. They're `EditableNode`. `hhast` ought to infer that some nodes children have types that are narrower than `EditableNode` but wider than a single node type (see `HackAstTypeGen`).

For example, `BinaryExpression::getLeftOperand` could return `IExpressionNode`, which is only implemented by the `EditableNode`s that represent Hack expressions.

**Comment by fredemmott** [comment]
Current list is here: https://github.com/hhvm/hhast/blob/master/src/__Private/codegen/CodegenSyntax.hack#L565

Needs more interfaces, and probably needs refactoring for readability when larger

**Comment by fredemmott** [comment]
Explicitly requested:
- [ ] expressions
- [ ] strings (single quoted, double quoted, heredoc, nowdoc)
- [ ] containers (including hack arrays)

**Comment by fredemmott** [comment]
Expressions: this also needs to /sometimes/ include `NameToken`, depending on the context - for example, a NameToken can be a class/function name, or it can be a constant. It's only valid as an expression when it's a constant.

HackAST creates 'fake' nodes in these situations based on the context

**Comment by fredemmott** [comment]
#176 copies over most of HackAST's list
