### ISSUE TITLE
Filter out invalid Hack files from child inference

### ISSUE THREAD

**Issue by hgoldstein** [hhvm/hhast#168]
`hhast` seems to think that the left operand of a `BinaryExpression` can be ... [tokens?](https://github.com/hhvm/hhast/blob/53fcae18aa00d234ba25959e7c71c6f792da8050/codegen/syntax/BinaryExpression.hack#L121) This is probably due to `hh_parse` being able to succeed at parsing files with errors, and even then reporting no errors for files with missing nodes. When inferring the node relations, we should:
- [x] Filter out files that have errors when parsed with `hh_parse`
- [x] Filter out files that are not valid Hack (fail a call to `hhvm -l`)

**Comment by fredemmott** [comment]
Done with d5e558cf

Some refactoring was needed - we don't run `hhvm -l` on every file; instead, after each file, we see if it inferred anything new. If so, we run `hhvm -l` on it.
