### ISSUE TITLE
Add `Tuple\from_async` => `concurrent {}` migration

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#175]
Expected in 4.5; this should be a port of the FB-internal ConcurrentCodemodScript

**Comment by fredemmott** [comment]
Docs: 
https://github.com/hhvm/user-documentation/pull/644

**Comment by lexidor** [comment]
`Tuple\from_async()` was removed from the HSL in 2019 https://github.com/hhvm/hsl/releases/tag/v4.36.0. There is no supported hhvm version with still runs a hsl version this old.
