### ISSUE TITLE
Add Specifier token promotion

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#185]
Part of #179

- [x] `foo(): noreturn` has a function type of just `token:noreturn`; this is very strange: no other tokens are seen there without wrapping, and noreturn is valid inside a simple_type_specifier; in the case of `foo(): this` ,there's a simpletypespecifier; in `foo(): Awaitable<noreturn>` there is also a simple type specifier. This should probably be addressed inside Hack's parser to remove this special edge case (FB T45648628)
- [x] cases like type_constant.type_constant_left_type should return `ITypeSpecifier`, which means that `token:name`, `token:parent`, `token:self`, and `token:this` need wrapping

Could either wrap into a dedicated wrapper class (like is done for IExpression), or SimpleTypeSpecifier might be directly usable

**Comment by hgoldstein** [comment]
HackAst just uses `SimpleTypeSpecifier`: that's almost certainly the intent. If you didn't want to use that you could emit special nodes: `ThisTypeSpecifier`, `SelfTypeSpecifier`, etc. That seems a bit ... much.

**Comment by fredemmott** [comment]
Both addressed in 2f67c09a69d3eb3065294b27b032f52792935500
