### ISSUE TITLE
Add linter banning explicitly final methods if the class is already final

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#191]
This can be a bit confusing in large files - if I see this, I assume that `foo()` can be overridden, but it can't if the class is final

```
public function foo(): void {
...
}

final public function bar(): void {
...
}
```

**Comment by lexidor** [comment]
Imma try this. If someone is already working on it, please tell me. 

If this message is a dinosaur when you read this at some point in the far future, I have forgotten about this. In that case, feel free to take a crack at it. :wink:
