### ISSUE TITLE
3.24: add `safe_pass_by_ref` migration

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#21]
This option will be supported in HHVM 3.23+; it requires that callsites specify '&' when passing an argument by ref; for example:

```Hack
$foo = vec[1,3,2];
sort(&$foo);
```

.hhconfig:

```
enable_experimental_tc_features=safe_pass_by_ref
```

With the option off, in 3.23+, the '&' is ignored - but it is an error in master. This can be worked on now if you build HHVM master, or `brew tap hhvm/hhvm; brew install hhvm-preview` if working on a mac.

This requires building support for migrations that query and fix typechecker errors, rather than purely operating on the AST

**Comment by ignacvucko** [comment]
This ends up highlighting hundreds of issues within hhvm source code itself when used with composer.

composer.json
{
  "require":
  {
    "facebook/xhp-lib": "2.x",
  }
}

$ hh_client
... dozens of errors ...
vendor/hhvm/hsl/src/c/select.php:180:21,32: This argument should be annotated with & (Typing[4168])
... dozens of errors ...


As far as I know, there isn't a way to ignore the vendor directory by adding it to your .hhconfig file.

So, how is the above best handled?

**Comment by fredemmott** [comment]
For now, you can use sed or similar to replace `/*ctpbr:&*/` in the HSL with `&`; I'll start talking to people next week about when we should switch what versions of HHVM HSL master should be targeting.
