### ISSUE TITLE
Documentation about writing Linter tests

### ISSUE THREAD

**Issue by vsiles** [hhvm/hhast#215]
Hi !
I'm trying to add a simple linter to warn users about some reserved syntax that might occur in their projects. The 'clean' examples test framework seems self-documented: One provides a vector of strings, each some valid code that should raise no errors. However I'm a bit lost on how to test the negative files, the one that should raise a warning/error. Is there any documentation on that ?

For the record, I'm writing an ASTLinter, not an AutoFixASTLinter.

**Comment by vsiles** [comment]
Ok I think I understand now (got confused by some naming patterns): for negative examples, one has to define some `.in` files in tests/examples following a naming convention. I think I'll try to write some doc about that once I'm done with my linter.

**Comment by jjergus** [comment]
https://github.com/hhvm/hhast/commit/7dbdd44797a6fd43726ce6f48039155fb3f38a6a added a "Testing" section to https://github.com/hhvm/hhast/blob/master/docs/linters-development.md

@fredemmott and @vsiles feel free to add anything I missed.
