### ISSUE TITLE
`hhast-migrate --empty-expression` precedence is incorrect

### ISSUE THREAD

**Issue by chaseajen** [hhvm/hhast#219]
running `hhast-migrate --empty-expression` replaces `empty($foo)` with `(!$foo ?? false)`, as `empty` is unsupported in HHVM 4.7+. however, the `!` takes precedence over the null coalesce, meaning notices are generated when `$foo` is undefined, whereas `empty($foo)` does not generate a notice when `$foo` is undefined.

instead, `empty($foo)` should be replaced with `!($foo ?? false)`.

some examples —
with `empty`:
```
hphpd> var_dump(empty($thing['bad']));
var_dump(empty($thing['bad']));
bool(true)
```

with existing migrator’s approach:
```
hphpd> var_dump((!$thing['bad'] ?? false));
var_dump(!$thing['bad'] ?? false);

Notice: Undefined variable: thing
bool(true)
```

with moved left paren to fix precedence:
```
hphpd> var_dump(!($thing['bad'] ?? false));
var_dump(!($thing['bad'] ?? false));
bool(true)
```

**Comment by jjergus** [comment]
Thanks for the report and sorry it took a while before I could get to it.

It should be fixed in HHAST 4.6.2
