### ISSUE TITLE
codemod toVector/Set/Map with new Vector/Set/Map

### ISSUE THREAD

**Issue by xulingc** [hhvm/hhast#229]
The API is being removed in https://github.com/facebook/hhvm/pull/8586

**Comment by lexidor** [comment]
These methods were indeed removed in the Q4 of 2019. https://hhvm.com/blog/2019/10/29/hhvm-4.29.html There is no supported hhvm version which still supports these methods. This was a good idea for a migration / codemod, but I don't think it ended up getting made.
