### ISSUE TITLE
Add linter against using PHP arrays etc as DataProvider return types

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#234]
`vec` and single-element tuples are now supported; types like `array<array<string>>` can now be `vec<(string)>`

Additionally, I think (but need to test) that HackTest 2 will work properly with non-integer keys - i.e. you could do `dict<string, (string)>` to allow you to provide a custom informative key for error messages.

**Comment by jjergus** [comment]
The linter could also check that the tuple matches the arguments of any test functions with that DataProvider.

**Comment by lexidor** [comment]
I am going to give this a shot.
If this post is prehistoric (:wave: hi, how's the future), feel free to bump me or give it a shot yourself.
I don't know if I'll be able to do the typechecking part between the test and the data provider, but this is a good start anyhow.
