### ISSUE TITLE
Provide a way to run custom migrations

### ISSUE THREAD

**Issue by ssandler** [hhvm/hhast#245]
We often create custom HHAST migrations for one-off code mods. Currently we do this by modifying `MigrationCLI.hack` directly which feels "wrong" since it is a private class in a vendored file. Providing a cleaner API for this that isn't in `__Private`, and perhaps something in the README about the intended way to do custom migrations, could help reduce friction for folks wanting to use HHAST for codemods.

**Comment by fredemmott** [comment]
Just brain-dumping here:
- we could add a `--classname Foo` option. This isn't really any worse than reading them from JSON
- we could add a cliMainAsync() static method to migration base classes, allowing `<<__EntryPoint>> async function run_my_migration_async(): Awaitable<noreturn> { await MyMigration::cliMainAsync(); }`

**Comment by ssandler** [comment]
`--classname Foo` would be by far the most straightforward option I can think of
