### ISSUE TITLE
add linter against shadowing local variables in foreach

### ISSUE THREAD

**Issue by jjergus** [hhvm/hhast#249]
This should be a lint error:

```hack
$value = 42;
// ...
foreach ($arr as $value) {
  // ...
}
```

Same for function arguments:

```hack
function foo(int $value) {
  // ...
  foreach ($arr as $value) {
    // ...
  }
}
```

**Comment by lexidor** [comment]
The HHClient linter hooks into `hh_client --lint` to enforce this rule. A custom linter in hhast is not needed anymore.
