### ISSUE TITLE
Unwanted cache files created in VS Code

### ISSUE THREAD

**Issue by xixixao** [hhvm/hhast#254]
I just launched VS Code in a folder with my hack files, and I got a dialog about using hhast. I confirmed it and in a sec it created bunch of files, which are now "messing" up my repo:
<img width="285" alt="Screenshot 2020-02-05 18 19 46" src="https://user-images.githubusercontent.com/1473433/73900406-7ff59b80-4844-11ea-9afc-53b403758200.png">
Is this expected? Can we store these somewhere else?

**Comment by xixixao** [comment]
At least I found a workaround: adding `**/*.hhast.parser-cache` to `Files: Exclude` in VS Code settings.

**Comment by fredemmott** [comment]
Yes, this is expected; there isn't really a better place for them than /somewhere/ in the repo - would putting them all under $REPO_ROOT/.hhast-cache/ be better?

**Comment by xixixao** [comment]
Yes, that would be definitely better.

That said, why do these files need to live in the repo? Why not /tmp/hash_of_hhconfigpath/ or some similar place?

**Comment by fredemmott** [comment]
hh_server currently does something like that, and it shouldn’t: it should be somewhere *user-specific* with automatic cleanup, an unpredictable path (so no re-use) or scoped to the repository so it’s easy to see where it goes. 

Centralized needs to also consider that there may be multiple checkouts

**Comment by xixixao** [comment]
Is this so important (slow?) that it can't be regenerated when I checkout a different commit?

I don't know what this actually does, but I presumed that it has to change when I change my code anyway?

I guess unpredictable path is ok too.

**Comment by fredemmott** [comment]
> Is this so important (slow?) that it can't be regenerated when I checkout a different commit?

Yes; it's a similar problem to when at FB saved states fail to load, except a new subprocess is needed for every single file in your repository - unless you run the linter on just one file at a time (this can be enabled in vscode-hack settings if you're not running it explicitly from the CLI).

Without this, if there is a crash, your IDE will just stop reporting lint issues (or removing ones you've fixed) for a large amount of time that scales linearly with the number of files in your project.

> I don't know what this actually does, but I presumed that it has to change when I change my code anyway?

Yes; it's the AST of your code in compressed JSON form. This replaces a subprocess call with a file read.

> I guess unpredictable path is ok too.

This removes the ability to re-use it between processes; it's one of the generally safe approaches for temporary files, but does lead to *every* restart.

**Comment by fredemmott** [comment]
> this can be enabled

Sorry, not quite: vscode can be configured to only lint files that you have open, rather than the entire project. This is usual behavior at FB, but if the performance benefits are unneeded, undesirable on projects that are entirely lint-clean.

**Comment by fredemmott** [comment]
@jjergus : let's do this whenever we next have to do a breaking change
