### ISSUE TITLE
[ License ] Many non-code files refer to `the BSD-style license`

### ISSUE THREAD

**Issue by lexidor** [hhvm/hhast#260]
This might be intentional, but many `.expect` and `.in` files say that this library is actually BSD licensed, but the [LICENSE](https://github.com/hhvm/hhast/blob/master/LICENSE) files says MIT.

But then again, the [CONTRIBUTING.md](https://github.com/hhvm/hhast/blob/master/CONTRIBUTING.md#license) file says BSD again.

**Comment by fredemmott** [comment]
Not intentional, working on fixing, and digging into why the internal (not-Hack-specific) linter didn't catch these.
