### ISSUE TITLE
Add linter to ban basic assignment in function parameters

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#39]
This is fairly common...

```
foo($bar = '123', $baz = '456');
```

... and has two main problems:

 - it's often done with the assumption that it's a real named parameter
 - it is often unexpected that it sets a local in the containing scope

This could be an autofixing-linter, suggesting this instead:

```
foo(/* bar = */ '123', /* baz = */ '456');
```

**Comment by wlin57** [comment]
starting

**Comment by wlin57** [comment]
done #48
