### ISSUE TITLE
Add linter for async function naming

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#4]
With the HSL, we're establishing a new convention for async functions (there's currently none):

 - async functions should end with either `_async` or `_asyncx`
 - async methods (both instance methods and static methods) should end with `Async` or `Asyncx`
 - should ignore functions that start with 'test'

This should be an AST-based linter, but should not support autofixing (as all the callsites would need updating too). It should use https://github.com/hhvm/hhast/blob/master/src/Linters/FunctionNamingLinterTrait.php -
https://github.com/hhvm/hhast/blob/master/src/Linters/CamelCasedMethodsUnderscoredFunctionsLinter.php may be a useful reference for this.

**Comment by wlin57** [comment]
done
