### ISSUE TITLE
[ Regression ] Mismatched configuration for a linter should fail the lint run

### ISSUE THREAD

**Issue by lexidor** [hhvm/hhast#405]
Repro:

Configure a linterConfig with an incorrect type (pass a string where an int is expected or alike). Run hhast-lint. Observe the lint run completing as normal. Expected result, exception bubbles up to the EntryPoint:

https://github.com/hhvm/hhast/blob/6087e969d02b7420f385a7a73486009d4cc3f792/src/__Private/LintRunConfig.hack#L271

**Comment by Atry** [comment]
Let me investigate why the exception is suppressed

**Comment by Atry** [comment]
Fixed in #412
