### ISSUE TITLE
Known bad HHClientLinters need to be automatically unconditionally suppressed

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#408]
See https://github.com/hhvm/hhast/pull/368#discussion_r742994307 and HackLintRule::HACK_LINT_IGNORED_CODES in FB www

This relates to #407 - we should never be raising 5583

**Comment by lexidor** [comment]
Is code [5607](https://github.com/facebook/hhvm/issues/8940) (identity comparison on disjoint types) on that list?

**Comment by fredemmott** [comment]
Nope, I think you found a new bug :)

**Comment by Atry** [comment]
> This relates to #407 - we should never be raising 5583

I created #419 to ignore 5583

**Comment by Atry** [comment]
Fixed in #419 and #422

**Comment by fredemmott** [comment]
For reference, the other codes in the FB list are either already deleted from the Ocaml code, or are in the 6xxx range; the 6xxx range requires Zoncolan, which is sadly not open source :(
