### ISSUE TITLE
Disable some lint rules by default

### ISSUE THREAD

**Issue by Atry** [hhvm/hhast#421]
This linter might also be good for the default blacklist - there's an ongoing discussion about removing it entirely at https://fb.workplace.com/groups/hackforhiphop/posts/7429940763721141

In short: It's accurate, but it's highly opinionated, and there's not consensus on the behavior it encourages being a good thing.

This isn't the same as the other codes we'd want to always-ignore, but "pretend it doesn't exist" may be the right thing to do for "may be deleted soon". Perhaps making it off-by-default but explicitly-includable may be better.

_Originally posted by @fredemmott in https://github.com/hhvm/hhast/pull/418#discussion_r766003467_

**Comment by lexidor** [comment]
What lint number are you referring to? Non-fb contributors can't access the link you posted.

**Comment by fredemmott** [comment]
Sorry, 5639 - I edited it into the orignal comment but didn't spot here.
