### ISSUE TITLE
Overrides are not respected with recent update

### ISSUE THREAD

**Issue by ssandler** [hhvm/hhast#441]
As of https://github.com/hhvm/hhast/commit/e6b406db4f4dbe0b7f6c53832d81e1e799faae87, the override functionality no longer handles multiple override rules matching the same file pattern. Example:

```
"overrides": [
		{
			"patterns": [
				"*foo/*",
				"*bar/*",
				"*baz/*"
			],
			"extraLinters": ["FooLinter"]
		},
		{
			"patterns": ["*foo/*"],
			"disabledLinters": ["BarLinter"]
		},
```

For files in `foo/`, we'll run the extra `FooLinter`, but `BarLinter` will not be disabled because the first rule that matches the fnmatch is the only one processed. Other matches are ignored due to `findOverride` processing only one result due to its usage of `C\find()`, whereas previously a `foreach` was used so that all overrides that matched would be processed.

**Comment by lexidor** [comment]
Fixed by https://github.com/hhvm/hhast/pull/550
