### ISSUE TITLE
Fix attribution for schema update commits

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#494]
The commits in https://github.com/hhvm/hhast/commits/update-schema/main are not authored by me, and if I remember correctly, I was not involved in the development of this automation. Please fix the committer information.

**Comment by Atry** [comment]
It seems that GitHub determines the author according to the git blame of the cron line in the Github action flow https://github.com/hhvm/hhast/blob/0a12574a6ddaafd3e3de7cf4508362f9955ea902/.github/workflows/build-and-test.yml#L6

**Comment by fredemmott** [comment]
Thanks; if this isn't based on the token, the easiest ways to change it would be `git config --global user.name FOO` and `git config --global user.email FOO` or the `GIT_AUTHOR_*`/`GIT_COMMITTER_*` variables at https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

It also might end up giving you more readable results to split out the update workflow from the main testing workflow

**Comment by zpao** [comment]
Ok, it looks like @Atry is likely right. Ignoring the issues with that…

We should probably pass an explicit author in these 2 cases. Not sure if it makes sense to do that in all cases or just if it's a scheduled job. Either way, you want to pass `author` in the `with` arguments to the action being run there. cf. https://github.com/peter-evans/create-pull-request#action-inputs

- https://github.com/hhvm/hhast/blob/main/.github/workflows/build-and-test.yml#L69-L75
- https://github.com/hhvm/hhast/blob/main/.github/workflows/build-and-test.yml#L100-L108

I don't know if y'all have a bot you're using (hhvm-bot had some issues IIRC), so could just make it facebook-github-bot if you want. `Facebook Community Bot <6422482@users.noreply.github.com>`

**Comment by Atry** [comment]
Or maybe hhvm-oss@fb.com
