### ISSUE TITLE
`--json` doesn't output range ends

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#64]
cc @PranayAgarwal

**Comment by PranayAgarwal** [comment]
Yeah, I left this open in the initial version because I didn't know what range end really meant for an error. It is probably something that individual linters will need to define.

**Comment by PranayAgarwal** [comment]
Or maybe it is possible to have overridable defaults (entire line/node)?

**Comment by fredemmott** [comment]
I think there can be defaults, but not in the base; line based linters could default to end of line, AST to end of node

**Comment by fredemmott** [comment]
https://github.com/hhvm/hhast/commit/dd72a267204915178124f5aab2be469b440415d6
