### ISSUE TITLE
Add linter for double-quoted strings

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#77]
Should not be on by default, but should be on when linters = all

Prefer single quoted strings. Exceptions:

- if the string contains quotation marks
- if the string contains interpolation
- if the string contains escape sequences (e.g. `"\n"`)

**Comment by lexidor** [comment]
I will give this a shot.
If this post is prehistoric (:wave: how's the future?) you may bump me or give it a shot yourself.
