### ISSUE TITLE
KeysetTypeSpecifier::getType() asserts that we get a `SimpleTypeSpecifier`, but other things are valid (e.g. `ClassnameTypeSpecifier`)

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#95]

**Comment by lexidor** [comment]
This issue has been fixed.
https://github.com/hhvm/hhast/blob/64782a555e3bf6b6da5c983cbf53ab2c63b4e4d9/codegen/syntax/KeysetTypeSpecifier.hack#L240-L252
